version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5661"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped
    command: sh -c "./wait-for-it.sh postgres:5432 -- npx prisma migrate deploy && npm run dev"

    networks:
      - hemoweb-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
    - hemoweb-net


  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - "5666:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hemoweb-net


volumes:
  postgres-data:

networks:
  hemoweb-net:
    driver: bridge



