version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5661"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build: ./frontend
    ports:
      - "5173:5662"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev -- --host

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hemoweb
    ports:
      - "5432:5666"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
